# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'youyou.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(988, 751)
        MainWindow.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(234, 249, 249), stop:1 rgba(1, 181, 180));\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 60, 951, 611))
        self.stackedWidget.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(234, 249, 249), stop:1 rgba(1, 181, 180));\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.TExt_Link = QtWidgets.QLabel(self.page1)
        self.TExt_Link.setGeometry(QtCore.QRect(320, 100, 441, 81))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(26)
        self.TExt_Link.setFont(font)
        self.TExt_Link.setStyleSheet("color:white;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0,0,0), stop:1 rgba(1, 181, 180));\n"
"")
        self.TExt_Link.setObjectName("TExt_Link")
        self.icone = QtWidgets.QLabel(self.page1)
        self.icone.setGeometry(QtCore.QRect(10, 70, 241, 211))
        self.icone.setStyleSheet("border-style:outset;\n"
"border-radius:12px;\n"
"border-width:1px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(234, 249, 249), stop:1 rgba(1, 181, 180));\n"
"\n"
"\n"
"")
        self.icone.setText("")
        self.icone.setPixmap(QtGui.QPixmap("../icone py/sitemayou/you.png"))
        self.icone.setObjectName("icone")
        self.caixa_link_2 = QtWidgets.QLineEdit(self.page1)
        self.caixa_link_2.setGeometry(QtCore.QRect(290, 260, 601, 61))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(16)
        self.caixa_link_2.setFont(font)
        self.caixa_link_2.setStyleSheet("border-style:outset;\n"
"border-radius:15px;\n"
"border-width:3px;\n"
"background-color:rgb(234, 249, 249)")
        self.caixa_link_2.setText("")
        self.caixa_link_2.setPlaceholderText("")
        self.caixa_link_2.setObjectName("caixa_link_2")
        self.radioButton_image = QtWidgets.QRadioButton(self.page1)
        self.radioButton_image.setGeometry(QtCore.QRect(100, 300, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        self.radioButton_image.setFont(font)
        self.radioButton_image.setStyleSheet("color: black;\n"
"alternate-background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 0, 255), stop:0.339795 rgba(255, 0, 0, 255), stop:0.339799 rgba(255, 255, 255, 255), stop:0.662444 rgba(255, 255, 255, 255), stop:0.662469 rgba(0, 0, 255, 255), stop:1 rgba(0, 0, 255, 255));")
        self.radioButton_image.setObjectName("radioButton_image")
        self.radioButton_musica = QtWidgets.QRadioButton(self.page1)
        self.radioButton_musica.setGeometry(QtCore.QRect(100, 340, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        self.radioButton_musica.setFont(font)
        self.radioButton_musica.setStyleSheet("color: black;\n"
"alternate-background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 0, 255), stop:0.339795 rgba(255, 0, 0, 255), stop:0.339799 rgba(255, 255, 255, 255), stop:0.662444 rgba(255, 255, 255, 255), stop:0.662469 rgba(0, 0, 255, 255), stop:1 rgba(0, 0, 255, 255));")
        self.radioButton_musica.setObjectName("radioButton_musica")
        self.radioButton_video_2 = QtWidgets.QRadioButton(self.page1)
        self.radioButton_video_2.setGeometry(QtCore.QRect(100, 380, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        self.radioButton_video_2.setFont(font)
        self.radioButton_video_2.setStyleSheet("color: black;\n"
"alternate-background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 0, 255), stop:0.339795 rgba(255, 0, 0, 255), stop:0.339799 rgba(255, 255, 255, 255), stop:0.662444 rgba(255, 255, 255, 255), stop:0.662469 rgba(0, 0, 255, 255), stop:1 rgba(0, 0, 255, 255));")
        self.radioButton_video_2.setObjectName("radioButton_video_2")
        self.baixa_link = QtWidgets.QPushButton(self.page1)
        self.baixa_link.setGeometry(QtCore.QRect(450, 450, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.baixa_link.setFont(font)
        self.baixa_link.setStyleSheet("border-style:outset;\n"
"border-radius:12px;\n"
"border-width:0px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 170, 0), stop:1 rgba(255, 255, 255, 255));")
        self.baixa_link.setObjectName("baixa_link")
        self.tela_2 = QtWidgets.QLabel(self.page1)
        self.tela_2.setGeometry(QtCore.QRect(460, 350, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tela_2.setFont(font)
        self.tela_2.setStyleSheet("color:white;\n"
"border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0,0,0), stop:1 rgba(1, 181, 180));\n"
"")
        self.tela_2.setText("")
        self.tela_2.setObjectName("tela_2")
        self.ver_link = QtWidgets.QPushButton(self.page1)
        self.ver_link.setGeometry(QtCore.QRect(230, 450, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.ver_link.setFont(font)
        self.ver_link.setStyleSheet("border-style:outset;\n"
"border-radius:12px;\n"
"border-width:0px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 170, 0), stop:1 rgba(255, 255, 255, 255));")
        self.ver_link.setObjectName("ver_link")
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.comboBox = QtWidgets.QComboBox(self.page2)
        self.comboBox.setGeometry(QtCore.QRect(420, 540, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icone py/user1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon, "")
        self.comboBox.addItem(icon, "")
        self.label_page2 = QtWidgets.QLabel(self.page2)
        self.label_page2.setGeometry(QtCore.QRect(600, 550, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(14)
        self.label_page2.setFont(font)
        self.label_page2.setText("")
        self.label_page2.setObjectName("label_page2")
        self.ver_link_2 = QtWidgets.QPushButton(self.page2)
        self.ver_link_2.setGeometry(QtCore.QRect(20, 470, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.ver_link_2.setFont(font)
        self.ver_link_2.setStyleSheet("border-style:outset;\n"
"border-radius:12px;\n"
"border-width:0px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 170, 0), stop:1 rgba(255, 255, 255, 255));")
        self.ver_link_2.setObjectName("ver_link_2")
        self.scrollArea_PAgina2 = QtWidgets.QScrollArea(self.page2)
        self.scrollArea_PAgina2.setGeometry(QtCore.QRect(30, 50, 881, 381))
        self.scrollArea_PAgina2.setStyleSheet("\n"
"background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.077, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));\n"
"border-radius:12px;\n"
"border-width:0px;\n"
"")
        self.scrollArea_PAgina2.setWidgetResizable(True)
        self.scrollArea_PAgina2.setObjectName("scrollArea_PAgina2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 881, 381))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Open_pagina2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.Open_pagina2.setStyleSheet("border-style:outset;\n"
"border-radius:12px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.Open_pagina2.setText("")
        self.Open_pagina2.setObjectName("Open_pagina2")
        self.gridLayout_3.addWidget(self.Open_pagina2, 0, 0, 1, 1)
        self.scrollArea_PAgina2.setWidget(self.scrollAreaWidgetContents_2)
        self.inputAbrirArquivo_2 = QtWidgets.QLineEdit(self.page2)
        self.inputAbrirArquivo_2.setGeometry(QtCore.QRect(240, 490, 521, 31))
        self.inputAbrirArquivo_2.setStyleSheet("border-style:outset;\n"
"border-radius:12px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 255, 255);")
        self.inputAbrirArquivo_2.setObjectName("inputAbrirArquivo_2")
        self.limpa_2 = QtWidgets.QPushButton(self.page2)
        self.limpa_2.setGeometry(QtCore.QRect(20, 540, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.limpa_2.setFont(font)
        self.limpa_2.setStyleSheet("border-style:outset;\n"
"border-radius:12px;\n"
"border-width:0px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 170, 0), stop:1 rgba(255, 255, 255, 255));")
        self.limpa_2.setObjectName("limpa_2")
        self.stackedWidget.addWidget(self.page2)
        self.pagina3 = QtWidgets.QWidget()
        self.pagina3.setObjectName("pagina3")
        self.scrollArea = QtWidgets.QScrollArea(self.pagina3)
        self.scrollArea.setGeometry(QtCore.QRect(20, 10, 881, 381))
        self.scrollArea.setStyleSheet("\n"
"background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.077, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));\n"
"border-radius:12px;\n"
"border-width:0px;\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 881, 381))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelImg = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelImg.setStyleSheet("border-style:outset;\n"
"border-radius:12px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.labelImg.setText("")
        self.labelImg.setObjectName("labelImg")
        self.gridLayout_2.addWidget(self.labelImg, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.inputAbrirArquivo = QtWidgets.QLineEdit(self.pagina3)
        self.inputAbrirArquivo.setGeometry(QtCore.QRect(40, 400, 521, 31))
        self.inputAbrirArquivo.setStyleSheet("border-style:outset;\n"
"border-radius:12px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 255, 255);")
        self.inputAbrirArquivo.setText("")
        self.inputAbrirArquivo.setObjectName("inputAbrirArquivo")
        self.btnEscolherArquivo = QtWidgets.QPushButton(self.pagina3)
        self.btnEscolherArquivo.setGeometry(QtCore.QRect(570, 400, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(16)
        self.btnEscolherArquivo.setFont(font)
        self.btnEscolherArquivo.setStyleSheet("border-style:outset;\n"
"border-radius:12px;\n"
"border-width:0px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 170, 0), stop:1 rgba(255, 255, 255, 255));")
        self.btnEscolherArquivo.setObjectName("btnEscolherArquivo")
        self.label = QtWidgets.QLabel(self.pagina3)
        self.label.setGeometry(QtCore.QRect(60, 440, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("border-style:outset;\n"
"border-radius:12px;\n"
"border-width:0px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 170, 0), stop:1 rgba(255, 255, 255, 255));")
        self.label.setObjectName("label")
        self.inputAltura = QtWidgets.QLineEdit(self.pagina3)
        self.inputAltura.setGeometry(QtCore.QRect(150, 530, 139, 21))
        self.inputAltura.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:black;\n"
"border-style:outset;\n"
"border-radius:8px;\n"
"border-width:0px;\n"
"")
        self.inputAltura.setObjectName("inputAltura")
        self.label_2 = QtWidgets.QLabel(self.pagina3)
        self.label_2.setGeometry(QtCore.QRect(60, 520, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-style:outset;\n"
"border-radius:12px;\n"
"border-width:0px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 170, 0), stop:1 rgba(255, 255, 255, 255));")
        self.label_2.setObjectName("label_2")
        self.inputLargura = QtWidgets.QLineEdit(self.pagina3)
        self.inputLargura.setGeometry(QtCore.QRect(150, 450, 141, 22))
        self.inputLargura.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:black;\n"
"border-style:outset;\n"
"border-radius:8px;\n"
"border-width:0px;\n"
"")
        self.inputLargura.setObjectName("inputLargura")
        self.btnRedimensionar = QtWidgets.QPushButton(self.pagina3)
        self.btnRedimensionar.setGeometry(QtCore.QRect(340, 450, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(16)
        self.btnRedimensionar.setFont(font)
        self.btnRedimensionar.setStyleSheet("border-style:outset;\n"
"border-radius:12px;\n"
"border-width:0px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 170, 0), stop:1 rgba(255, 255, 255, 255));")
        self.btnRedimensionar.setObjectName("btnRedimensionar")
        self.btnSalvar = QtWidgets.QPushButton(self.pagina3)
        self.btnSalvar.setGeometry(QtCore.QRect(340, 520, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(16)
        self.btnSalvar.setFont(font)
        self.btnSalvar.setStyleSheet("border-style:outset;\n"
"border-radius:12px;\n"
"border-width:0px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 170, 0), stop:1 rgba(255, 255, 255, 255));")
        self.btnSalvar.setObjectName("btnSalvar")
        self.limpa_3 = QtWidgets.QPushButton(self.pagina3)
        self.limpa_3.setGeometry(QtCore.QRect(610, 480, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.limpa_3.setFont(font)
        self.limpa_3.setStyleSheet("border-style:outset;\n"
"border-radius:12px;\n"
"border-width:0px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 170, 0), stop:1 rgba(255, 255, 255, 255));")
        self.limpa_3.setObjectName("limpa_3")
        self.stackedWidget.addWidget(self.pagina3)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 0, 951, 81))
        self.frame.setStyleSheet("\n"
"\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0,0,0), stop:1 rgba(1, 181, 180));\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_page_1 = QtWidgets.QPushButton(self.frame)
        self.btn_page_1.setGeometry(QtCore.QRect(20, 10, 101, 41))
        self.btn_page_1.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_1.setStyleSheet("color:white;\n"
"border-style:outset;\n"
"border-radius:8px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 170, 0);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icone py/icons/cil-check-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_page_1.setIcon(icon1)
        self.btn_page_1.setObjectName("btn_page_1")
        self.btn_page_3 = QtWidgets.QPushButton(self.frame)
        self.btn_page_3.setGeometry(QtCore.QRect(340, 10, 111, 41))
        self.btn_page_3.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_3.setStyleSheet("color:white;\n"
"border-style:outset;\n"
"border-radius:8px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 170, 0);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icone py/icons/cil-touch-app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_page_3.setIcon(icon2)
        self.btn_page_3.setObjectName("btn_page_3")
        self.btn_page_2 = QtWidgets.QPushButton(self.frame)
        self.btn_page_2.setGeometry(QtCore.QRect(170, 10, 139, 40))
        self.btn_page_2.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_2.setStyleSheet("color:white;\n"
"border-style:outset;\n"
"border-radius:8px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 170, 0);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../icone py/icons/cil-people.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_page_2.setIcon(icon3)
        self.btn_page_2.setObjectName("btn_page_2")
        self.frame.raise_()
        self.stackedWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 988, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.actionpagina = QtWidgets.QAction(MainWindow)
        self.actionpagina.setObjectName("actionpagina")

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.limpa_2.clicked.connect(self.Open_pagina2.clear)
        self.limpa_2.clicked.connect(self.inputAbrirArquivo_2.clear)
        self.limpa_3.clicked.connect(self.labelImg.clear)
        self.limpa_3.clicked.connect(self.inputAltura.clear)
        self.limpa_3.clicked.connect(self.inputLargura.clear)
        self.limpa_3.clicked.connect(self.inputAbrirArquivo.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TExt_Link.setText(_translate("MainWindow", "  DIGITE O LINK ABAIXO"))
        self.radioButton_image.setText(_translate("MainWindow", "Image"))
        self.radioButton_musica.setText(_translate("MainWindow", "Musica"))
        self.radioButton_video_2.setText(_translate("MainWindow", "Video"))
        self.baixa_link.setText(_translate("MainWindow", "Baixar"))
        self.ver_link.setText(_translate("MainWindow", "Visualizar"))
        self.comboBox.setItemText(1, _translate("MainWindow", "China"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Brasil"))
        self.ver_link_2.setText(_translate("MainWindow", "Ver"))
        self.limpa_2.setText(_translate("MainWindow", "Limpar"))
        self.inputAbrirArquivo.setPlaceholderText(_translate("MainWindow", "Caminho da foto"))
        self.btnEscolherArquivo.setText(_translate("MainWindow", "Escolher Arquivo"))
        self.label.setText(_translate("MainWindow", "Largura"))
        self.inputAltura.setPlaceholderText(_translate("MainWindow", "Coloque Altura"))
        self.label_2.setText(_translate("MainWindow", "Altura"))
        self.inputLargura.setPlaceholderText(_translate("MainWindow", "Coloque Largura"))
        self.btnRedimensionar.setText(_translate("MainWindow", "Redimensionar"))
        self.btnSalvar.setText(_translate("MainWindow", "Salvar"))
        self.limpa_3.setText(_translate("MainWindow", "Limpar"))
        self.btn_page_1.setText(_translate("MainWindow", "pagina1"))
        self.btn_page_3.setText(_translate("MainWindow", "Page 3"))
        self.btn_page_2.setText(_translate("MainWindow", "pagina2"))
        self.actionpagina.setText(_translate("MainWindow", "pagina"))
