# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prodruto_p.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_estoque(object):
    def setupUi(self, estoque):
        estoque.setObjectName("estoque")
        estoque.resize(607, 368)
        estoque.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:rgb(1, 181, 180)")
        self.centralwidget = QtWidgets.QWidget(estoque)
        self.centralwidget.setObjectName("centralwidget")
        self.Codigo = QtWidgets.QLabel(self.centralwidget)
        self.Codigo.setGeometry(QtCore.QRect(80, 70, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Codigo.setFont(font)
        self.Codigo.setTabletTracking(False)
        self.Codigo.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Codigo.setAutoFillBackground(False)
        self.Codigo.setStyleSheet("border-style:outset;\n"
"border-radius:8px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 170, 0);")
        self.Codigo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Codigo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Codigo.setLineWidth(8)
        self.Codigo.setMidLineWidth(3)
        self.Codigo.setTextFormat(QtCore.Qt.PlainText)
        self.Codigo.setWordWrap(False)
        self.Codigo.setObjectName("Codigo")
        self.Descricao = QtWidgets.QLabel(self.centralwidget)
        self.Descricao.setGeometry(QtCore.QRect(80, 120, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Descricao.setFont(font)
        self.Descricao.setTabletTracking(False)
        self.Descricao.setStyleSheet("border-style:outset;\n"
"border-radius:8px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 170, 0);")
        self.Descricao.setObjectName("Descricao")
        self.Quant = QtWidgets.QLabel(self.centralwidget)
        self.Quant.setGeometry(QtCore.QRect(80, 170, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Quant.setFont(font)
        self.Quant.setStyleSheet("border-style:outset;\n"
"border-radius:8px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 170, 0);")
        self.Quant.setObjectName("Quant")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 220, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_4.setStyleSheet("border-style:outset;\n"
"border-radius:8px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 170, 0);")
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setObjectName("label_4")
        self.codigo_p = QtWidgets.QLineEdit(self.centralwidget)
        self.codigo_p.setGeometry(QtCore.QRect(170, 70, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.codigo_p.setFont(font)
        self.codigo_p.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:rgb(234, 249, 249)")
        self.codigo_p.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.codigo_p.setText("")
        self.codigo_p.setClearButtonEnabled(False)
        self.codigo_p.setObjectName("codigo_p")
        self.descricao_p = QtWidgets.QLineEdit(self.centralwidget)
        self.descricao_p.setGeometry(QtCore.QRect(170, 120, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.descricao_p.setFont(font)
        self.descricao_p.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:rgb(234, 249, 249)")
        self.descricao_p.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.descricao_p.setText("")
        self.descricao_p.setClearButtonEnabled(False)
        self.descricao_p.setObjectName("descricao_p")
        self.quant_p = QtWidgets.QLineEdit(self.centralwidget)
        self.quant_p.setGeometry(QtCore.QRect(170, 170, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.quant_p.setFont(font)
        self.quant_p.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:rgb(234, 249, 249)")
        self.quant_p.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.quant_p.setText("")
        self.quant_p.setClearButtonEnabled(False)
        self.quant_p.setObjectName("quant_p")
        self.valor_p = QtWidgets.QLineEdit(self.centralwidget)
        self.valor_p.setGeometry(QtCore.QRect(170, 220, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.valor_p.setFont(font)
        self.valor_p.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:rgb(234, 249, 249)")
        self.valor_p.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.valor_p.setText("")
        self.valor_p.setClearButtonEnabled(False)
        self.valor_p.setObjectName("valor_p")
        self.cadastro_p = QtWidgets.QPushButton(self.centralwidget)
        self.cadastro_p.setGeometry(QtCore.QRect(380, 280, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.cadastro_p.setFont(font)
        self.cadastro_p.setStyleSheet("border-style:outset;\n"
"border-radius:8px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 170, 0);")
        self.cadastro_p.setObjectName("cadastro_p")
        self.apagar_p = QtWidgets.QPushButton(self.centralwidget)
        self.apagar_p.setGeometry(QtCore.QRect(50, 280, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.apagar_p.setFont(font)
        self.apagar_p.setStyleSheet("border-style:outset;\n"
"border-radius:8px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 170, 0);")
        self.apagar_p.setObjectName("apagar_p")
        self.altera = QtWidgets.QPushButton(self.centralwidget)
        self.altera.setGeometry(QtCore.QRect(210, 280, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.altera.setFont(font)
        self.altera.setStyleSheet("border-style:outset;\n"
"border-radius:8px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 170, 0);")
        self.altera.setObjectName("altera")
        self.id_produto = QtWidgets.QLabel(self.centralwidget)
        self.id_produto.setGeometry(QtCore.QRect(60, 10, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.id_produto.setFont(font)
        self.id_produto.setTabletTracking(False)
        self.id_produto.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.id_produto.setAutoFillBackground(False)
        self.id_produto.setStyleSheet("border-style:outset;\n"
"border-radius:8px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 170, 0);")
        self.id_produto.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.id_produto.setFrameShadow(QtWidgets.QFrame.Plain)
        self.id_produto.setLineWidth(8)
        self.id_produto.setMidLineWidth(3)
        self.id_produto.setTextFormat(QtCore.Qt.PlainText)
        self.id_produto.setWordWrap(False)
        self.id_produto.setObjectName("id_produto")
        self.id_produto_p = QtWidgets.QLineEdit(self.centralwidget)
        self.id_produto_p.setGeometry(QtCore.QRect(120, 10, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.id_produto_p.setFont(font)
        self.id_produto_p.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:rgb(234, 249, 249)")
        self.id_produto_p.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.id_produto_p.setText("")
        self.id_produto_p.setClearButtonEnabled(False)
        self.id_produto_p.setObjectName("id_produto_p")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(200, 10, 381, 41))
        self.lineEdit.setObjectName("lineEdit")
        estoque.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(estoque)
        self.statusbar.setObjectName("statusbar")
        estoque.setStatusBar(self.statusbar)

        self.retranslateUi(estoque)
        self.apagar_p.clicked.connect(self.valor_p.clear)
        self.apagar_p.clicked.connect(self.quant_p.clear)
        self.apagar_p.clicked.connect(self.descricao_p.clear)
        self.apagar_p.clicked.connect(self.codigo_p.clear)
        QtCore.QMetaObject.connectSlotsByName(estoque)

    def retranslateUi(self, estoque):
        _translate = QtCore.QCoreApplication.translate
        estoque.setWindowTitle(_translate("estoque", "MainWindow"))
        self.Codigo.setText(_translate("estoque", " Codigo"))
        self.Descricao.setText(_translate("estoque", "Descriçao"))
        self.Quant.setText(_translate("estoque", "Quantidade"))
        self.label_4.setText(_translate("estoque", "Valor"))
        self.codigo_p.setPlaceholderText(_translate("estoque", "CODIGO PRODUTO"))
        self.descricao_p.setPlaceholderText(_translate("estoque", "DESCRIÇAO "))
        self.quant_p.setPlaceholderText(_translate("estoque", "QUANTIDADE"))
        self.valor_p.setPlaceholderText(_translate("estoque", "VALOR"))
        self.cadastro_p.setText(_translate("estoque", "Salvar"))
        self.apagar_p.setText(_translate("estoque", "Apagar"))
        self.altera.setText(_translate("estoque", "Altera"))
        self.id_produto.setText(_translate("estoque", "     ID"))
        self.id_produto_p.setPlaceholderText(_translate("estoque", "ID PRODUTO"))
        self.lineEdit.setText(_translate("estoque", "NAO PREENCHAR ID SO COLOCA QUANDO DESEJA APAGA ITEM OU ALTERA"))
